version: '3'
services:
  latex-docker:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/home/docker/work
      - ./.latexmkrc:/home/docker/.latexmkrc
      - ./indentconfig.yml:/home/docker/indentconfig.yaml
    tty: true